name: NossoDinDin
description: "Um aplicativo de finanças pessoais para controle de gastos e receitas."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.0.0
  provider: any
  cupertino_icons: ^1.0.8
  material_symbols_icons: ^4.2780.0
  image_picker: ^1.0.7
  uuid: ^4.0.0
  permission_handler: ^11.3.1
  
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  path: ^1.8.3
  
  http: ^1.2.0
  
  fl_chart: ^0.68.0
  
  intl: ^0.20.2

  
  formz: ^0.6.1
  
  decimal: ^3.0.2
  
  animations: ^2.0.11
  shimmer: ^3.0.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo-NossoDinDin.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo-NossoDinDin.png"
