name: Deploy Flutter Web App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
    
    - name: Enable Flutter Web
      run: flutter config --enable-web
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build web app
      run: flutter build web --release --web-renderer canvaskit
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
        cname: nossodindin.exemplo.com  # Substitua pelo seu domínio personalizado
