name: Build Flutter Web

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        cache: true
        
    - name: Enable Flutter Web
      run: flutter config --enable-web
      
    - name: Clean project
      run: flutter clean
      
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build Flutter Web
      run: flutter build web --release --web-renderer html --base-href "/Finan-as-Pessoais/"
      
    - name: Add .nojekyll file
      run: touch build/web/.nojekyll
      
    - name: Deploy to docs folder
      run: |
        rm -rf docs
        cp -r build/web docs
        
    - name: Commit and push docs
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Update docs folder with Flutter web build"
          git push
        else
          echo "No changes to commit"
        fi
